[package]
name = "tutorial_breakout"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6"
crossterm = { version = "0.28", features = ["event-stream"] }
futures = "0.3"
ratatui = "0.29"
tokio = { version = "1.42", features = ["full"] }
tokio-util = "0.7"
